modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mod_centuplex"
version="1.0.0"
displayName="mod centuplex"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Utente PC, MCreator"

[[dependencies.mod_centuplex]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




